vich_uploader:
    db_driver: orm
    mappings:
        events_image:
            uri_prefix: /images/events
            upload_destination: "%kernel.project_dir%/public/images/events"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
